#!/bin/sh
# Starts and stops x11vnc
#


case "$1" in
start)

start-stop-daemon --start --exec /usr/bin/x11vnc -- -sleepin 30 -forever -rfbport 5900

cd 
;;

stop)

start-stop-daemon --stop --exec /usr/bin/x11vnc 

;;

restart)
$0 stop
$0 start
;;

status)
if pidof -o %PPID x11vnc > /dev/null; then
echo "Running"
exit 0
else
echo "Not running"
exit 1
fi
;;

*)
echo "Usage: $0 {start|stop|restart|status}"
exit 1
esac